### ISSUE TITLE
PhantomJS error thrown when run pointed at offline domain

### ISSUE THREAD

**Issue by Raijinn-XIII** [TheJaredWilcurt/UGUI-pa11y#1]
![ugui](https://cloud.githubusercontent.com/assets/5169776/21556429/5b08dc20-cdee-11e6-9cec-9367cae25e32.png)

This error doesn't impede the user from accessing the tool's results, but an exception may need to be defined in the wrapper for this case. Also, I didn't see this error in any other case but to an offline domain.

Let me know if more info is needed.

**Comment by TheJaredWilcurt** [comment]
Fixed. Errors now display whatever the error message is.
