### ISSUE TITLE
parse sitemap

### ISSUE THREAD

**Issue by DanielRuf** [TheJaredWilcurt/UGUI-pa11y#38]
It would be useful to parse a sitemap of a domain to test all subpages / onsite links.

**Comment by TheJaredWilcurt** [comment]
Koa11y 4 is will be a complete redesign. It is planned to include a project based system so you can have a site and multiple pages under it.

This feature request would not meet MVP for the new version, but could go in to a later release after 4.0.0.

**Comment by DanielRuf** [comment]
Right. I'll probably provide a PR with the feature based on v4 and join the design discussions later this year to help with the integration of it.
