### ISSUE TITLE
What is the importance of warnings and notices

### ISSUE THREAD

**Issue by jasan-s** [TheJaredWilcurt/UGUI-pa11y#41]
I may have missed this but I couldn't find info regarding the matter. Errors in the report are clear that need fixing. but what what about the warnings and notices? Do they require fixing to be compliant?

**Comment by TheJaredWilcurt** [comment]
* **Errors:** Known to be in violation.
* **Warnings:** Can't detect with certainty if it is a violation, but probably is.
* **Notices:** May be in violation, or may be perfectly fine. Depends entirely on context.

For example, a `<table>` that is used to display tabular data (like an excel spreadsheet), should have a caption associated with it to summarize the table's contents. However if the `<table>` is being used for page layout reasons, then no caption is required. The context of how you are using the table is difficult to accurately understand programmatically, so a **notice** is issued to instruct you to look into the context of this code to determine if it is in violation.

Under the hood Koa11y uses [Pa11y](http://pa11y.org) to detect these Errors/Warnings/Violations. But if you dig deeper, Pa11y is actually using [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/). HTML_CodeSniffer is what is generating the distinction between Errors, Warnings, and Notices. You can read more here:

* http://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/
* http://squizlabs.github.io/HTML_CodeSniffer/Standards/Section508/
