### ISSUE TITLE
Error through corporate proxy

### ISSUE THREAD

**Issue by technolytic** [TheJaredWilcurt/UGUI-pa11y#43]
Dear all,

I'm on Fedora 26 **behind a corporate proxy**.
I get the following error with Koa11y v3.0.0 at startup when running it on http://google.com

![error_koa11y](https://user-images.githubusercontent.com/4247958/35558996-c39c868a-05a9-11e8-9c5f-d4fae152e341.png)

In the console:

```
app.js:718 
Error: Error opening url "http://google.com" : Host google.com not found
    at Object.<anonymous> (/(...)/Koa11y-3.0.0/node_modules/truffler/lib/truffler.js:154:18)
    at /(...)/Koa11y-3.0.0/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/(...)/Koa11y-3.0.0/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

However, Pa11y in command-line ( `./node_modules/pa11y/bin/pa11y http://google.com `) runs fine.

I assume that I need to pass proxy settings to pa11y, how could I do that?
In `koa11y-settings.json` file?                                                                      

Thanks for your help!

**Comment by TheJaredWilcurt** [comment]
You can edit the local copy of Koa11y you have. Find this file `_scripts/app.js` and replace the lines [708-716](https://github.com/open-indy/Koa11y/blob/3.0/_scripts/app.js#L708) with this:

```js
var pallyOptions = Object.assign({}, {
    'phantom': {
        'parameters': {
            'proxy': '1.2.3.4:8080',
            'proxy-type': 'http|socks5|none',
            'proxy-auth': 'username:password'
        }
    },
    'phantomjs': {
        'path': phantomjs.path
    },
    'allowedStandards': [standard],
    'standard': standard,
    'reporter': filetype,
    'ignore': ignore
});
```
The Phantom params are based on this:

* [Pa11y Troublshooting: Proxies](https://github.com/pa11y/pa11y/blob/db83649030901de5dff058aeaeca3ea370adfb01/TROUBLESHOOTING.md#how-can-i-use-pa11y-with-a-proxy-server)

Obviously, you'll need to change the proxy parameters to whatever works for you:

```js
var pallyOptions = Object.assign({}, {
    'phantom': {
        'parameters': {
            'proxy': '192.168.1.20:8000',
            'proxy-type': 'http',
            'proxy-auth': 'jwilcurt:P4ssw0rd1'
        }
    },
    'phantomjs': {
        'path': phantomjs.path
    },
    'allowedStandards': [standard],
    'standard': standard,
    'reporter': filetype,
    'ignore': ignore
});
```

**Comment by technolytic** [comment]
Thank for your detailed response, it works perfectly. 
It also helps me to fix other settings for PhantomJS if needed.
Great job & thank again!
