### ISSUE TITLE
npm install error package.json not found

### ISSUE THREAD

**Issue by ckcjam** [TheJaredWilcurt/UGUI-pa11y#44]
I'm on a Mac and my experience has always been in a windows environment and need help getting this application installed on my mac.
sh-3.2# npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/charlescarter/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/charlescarter/package.json'
npm WARN charlescarter No description
npm WARN charlescarter No repository field.
npm WARN charlescarter No README data
npm WARN charlescarter No license field.

**Comment by TheJaredWilcurt** [comment]
@ckcjam 

You should just be able to download the OSX version, unzip it, and double-click.

* https://github.com/open-indy/Koa11y/releases

Here's a video showing how:

* https://www.youtube.com/watch?v=yoJDb018Edc&t=1m47s

You only need Node or NPM if you want to run Koa11y's source code local to develop Koa11y. Also, from your error, you tried to run `npm install` from your user profile. You should be running it from inside of the project folder (the folder containing `package.json`). You can move to that location by typing `cd ` into the terminal, and then drag/drop your folder into the terminal and press enter. Then you can run `npm install` and `npm start` on any Node based project.
