### ISSUE TITLE
Travis CI is not used

### ISSUE THREAD

**Issue by DanielRuf** [TheJaredWilcurt/UGUI-pa11y#46]
There is a Travis CI config but it seems to be unused. Is it obsolete or just not enabled for this repo?

**Comment by TheJaredWilcurt** [comment]
Yeah, I wanted to use it, however I don't control the `open-indy` github org, I was just given a repo under it to host this project. The org itself has to allow 3rd parties (like Travis CI) to access it's stuff. So that just never happened.
