### ISSUE TITLE
Testing web pages that need user login

### ISSUE THREAD

**Issue by regnard** [TheJaredWilcurt/UGUI-pa11y#47]
Is there a way to use Koa11y for pages that need a user to be logged in?

**Comment by TheJaredWilcurt** [comment]
Koa11y does not have this functionality. It is built on top of Pa11y, which is a command line tool. the latest versions of Pa11y do allow for this though. You can look into using Pa11y directly:

* http://pa11y.org

**Comment by DanielRuf** [comment]
basicauth support was added to the branch for koa11y 3

See https://github.com/open-indy/Koa11y/commit/2a1003b995391a9b3040fdb0cbc3bb2d0af1c9c5

But this is not released as a binary release.
So you may have to create your own build.

Here are the builds for Windows and macOS: https://github.com/DanielRuf/Koa11y-prebuilt

**Comment by davelloper** [comment]
great job DanielRuf, this is really a useful addition that we will use. Thanks for integrating the function. Once it reaches the binary release, lots of people are going to be happy.
