### ISSUE TITLE
Is Koa11y still active?

### ISSUE THREAD

**Issue by bgarrant** [TheJaredWilcurt/UGUI-pa11y#50]
Is Koa11y still under active development? Just wondering if I should use Pa11y if so.

**Comment by TheJaredWilcurt** [comment]
At the moment, no.

The team that was working on it has disbanded, and I'm busy with other projects. I may come back to this in the future to update it and put out a new release, but for now, it is what it is.

**Comment by bgarrant** [comment]
Thanks for getting back to me.  Hope to see Koa11y in the future.
