### ISSUE TITLE
Disabled Human Testers Available?

### ISSUE THREAD

**Issue by oflak** [TheJaredWilcurt/UGUI-pa11y#53]
I care a lot about accessibility and would love to have some "real humans" to check my websites additionally to automated tools like Koa11y.
Where can I find them?
Maybe Koa11y can help to bring website builders and disabled users together?
Thanks!

**Comment by TheJaredWilcurt** [comment]
This is a small project, you'd be better off looking into A11y communities:

* https://webaim.org/community/
