### ISSUE TITLE
Koally GUI is not loading

### ISSUE THREAD

**Issue by Tigress2019** [TheJaredWilcurt/UGUI-pa11y#54]
Hi

I have downloaded the Koally package for Windows.

But Koally GUI is not loading and coming as distorted Refer below screenshot
![image](https://user-images.githubusercontent.com/56587181/66828020-a928ae00-ef6d-11e9-8ef0-48195ff71c7b.png)

**Comment by TheJaredWilcurt** [comment]
Delete and redownload. All files required are shipped with it, there should be no problems rendering anything. I'm assuming the package was corrupted during download or unzipping.

**Comment by Tigress2019** [comment]
Perfect! Thank You!
