### ISSUE TITLE
Critical error at the first start of application: can’t load libexif

### ISSUE THREAD

**Issue by OlgaTCK** [TheJaredWilcurt/UGUI-pa11y#55]
Error during the first start of application, “debug” txt-file auto-created: **_

[1024/202034:ERROR:image_metadata_extractor.cc(114)] Couldn't load libexif. 126

_**

**Full description:** Error log created automatically during the first start of the application - After the download and extraction of zip-files directly into root folder (C:\) or into a deeply nested subfolder (C:\Users\xxx\Downloads\xxx\WIN_Koa11y_3.0.0\Koa11y). Error log txt-file “debug” will be created in the folder of application files.

**Expected result:** Successful first start of application
**Actual result:** Error log: “debug”-txt file during the first start of application

**Steps to reproduce:**
1)	Download Koa11y v3.0.0 for Windows from the Koa11y Website: https://open-indy.github.io/Koa11y/
2)	Extract everything from the downloaded zip-file into any folder on Windows 10.
3)	Start application from the extracted archive via double-click: use file named  “Koa11y”, type: Application. 
4)	Application “Koa11y”: Desktop version starts and GUI opens.  Error logging file “debug.txt” is simultaneously created in the folder containing extracted zip-archive of Koa11y Desktop app.
**Defect:** 
Application can’t load “libexif” as part of it’s core functionality and is unable to start properly. Error log “debug”-txt documents it during the first start of application

**Reproducability:** always on OS Windows 10, x64
**Severity:** critical (potentially disabls key functionality)

[debug.log](https://github.com/open-indy/Koa11y/files/3854354/debug.log)
@TheJaredWilcurt @jamesboyer92 @robgaston1 @mardisworld

**Comment by TheJaredWilcurt** [comment]
@OlgaTCK This is intentional.

Koa11y runs on top of NW.js which ships with many files. Some of these files are only needed for specific functionality, like displaying a PDF in the app, playing video, or rendering a 3D model with OpenGL/WebGL. 

Since Koa11y does not utilize these functions, those files were removed to reduce the overall size of the distribution of the app. The app functions perfectly, the only side-effect is that a debug text file is generated on first run.

**Comment by OlgaTCK** [comment]
> @OlgaTCK This is intentional.
> 
> Koa11y runs on top of NW.js which ships with many files. Some of these files are only needed for specific functionality, like displaying a PDF in the app, playing video, or rendering a 3D model with OpenGL/WebGL.
> 
> Since Koa11y does not utilize these functions, those files were removed to reduce the overall size of the distribution of the app. The app functions perfectly, the only side-effect is that a debug text file is generated on first run.

Thanks for a fast reply, @TheJaredWilcurt. It's good to know that it's intentional. I thought, it might be the reason why the app missbehaves afterwards, like e.g.: from some point on, a11y reports contain only image a11y details, no info about errors, warnings and tips for improvement. Another example is no loading of Imgs and their respective Alts, showing of placeholders instead when manually check is performed.

**Comment by OlgaTCK** [comment]
> @OlgaTCK This is intentional.
> 
> Koa11y runs on top of NW.js which ships with many files. Some of these files are only needed for specific functionality, like displaying a PDF in the app, playing video, or rendering a 3D model with OpenGL/WebGL.
> 
> Since Koa11y does not utilize these functions, those files were removed to reduce the overall size of the distribution of the app. The app functions perfectly, the only side-effect is that a debug text file is generated on first run.

According to the libexif-description at https://sourceforge.net/projects/libexif/ , libexif is the EXIF Tag Parsing Library and "EXIF files are JPEG files with extra tags that contain information about the image. The EXIF library allows you to parse an EXIF file and read the data from those tags", 
but they don't mention metadata tags of audio files for some reason...  I am wondering if Koa11y is using EXIFs of images from libexif and if EXIFs could also be a source for image a11y description tags like "Alt"-descriptions. Would be interesting to know your opinion.
