### ISSUE TITLE
No loading of Imgs and their respective Alts, placeholders instead

### ISSUE THREAD

**Issue by OlgaTCK** [TheJaredWilcurt/UGUI-pa11y#56]
What can I do, when instead of loading Imgs and their respective Alts that enables manually check for Alts’ description informativeness (image a11y section in the Koa11y v3.0.0), there are only placeholders instead? Screanshot attached.

As workaround, I loaded the website before and refreshed it prior to the concole code pasting, scrolled down through the whole page and clicked through all the carussels, but images / except the logo with its description / did not load for a11y check. 
The URL used: https://www.business-punk.com
System: Win10, x64
Koa11y v3.0.0

![D6](https://user-images.githubusercontent.com/57837667/69478008-3e855080-0dfe-11ea-8d7c-6c239651ab21.png)

**Comment by TheJaredWilcurt** [comment]
Working as expected. Your page is lazy-loading images in a non-accessible way.

![Screenshot of the page and the DOM](https://user-images.githubusercontent.com/4629794/69495768-835dc580-0e98-11ea-89cf-75232f0266f8.png)

If you look in the DOM, the JS waits until the content is scrolled into view, then it sets the background image of the parent element to a predetermined (stored in `data-interchange``). The image `src` stays as a dummy "placeholder", transparent image, while the parent div's background is visually displayed.

The script you run provided by Koa11y only grab's the `img`'s `src` and `alt` attribute values. It does not look at any other elements. Nor should it, as the goal is to check the accessibility of the images.

Even if no images load, you can already tell that `placeholder` is not a descriptive text of the image.

**Comment by OlgaTCK** [comment]
Sorry, I don't get it right. You say, it is OK, though, but if this manually step of checking is done, there is only description of the img a11y check section, and nothing about errors, warnings or tips for improvement. Is this also the expected behavioral of the Koa11y app?

The HTML report generated only this:

https://www.business-punk.com
Image Accessibility
 10% of images on the page had descriptive ALT text. (3/31)
 100% of ALTs were under 100 characters. (31/31)
 94% of images were under 100KB in size. (29/31)
 100% of images loaded with a total image payload of 1205.7KB (31/31)
