### ISSUE TITLE
still actively maintained?

### ISSUE THREAD

**Issue by DanielRuf** [TheJaredWilcurt/UGUI-pa11y#59]
It seems Koa11y is not actively maintained anymore. The last commit was over 2 years ago.

See also https://github.com/open-indy/Koa11y/issues/50

**Comment by TheJaredWilcurt** [comment]
No changes from that post. this has been a low priority, and will remain so until it becomes significantly outdated to the point that it requires the attention. Such as if WCAG 3 comes out. In the mean time, Koa11y should still function pretty well for it's original use case. and the underlying technologies (pa11y) are still available as an alternative.

* https://pa11y.org
