### ISSUE TITLE
Website speed issue

### ISSUE THREAD

**Issue by josh319** [TheJaredWilcurt/UGUI-pa11y#64]
I recently launched a website named [https://www.miscof.com/](https://www.miscof.com/) which causing serious speed issue and takes too much time to load.

**Comment by TheJaredWilcurt** [comment]
worked fine for me. WCAG 2.0 AA report attached

* [miscof.com.html.zip](https://github.com/open-indy/Koa11y/files/5792877/miscof.com.zip)
